import { useState } from 'react';
import { notificationCategories, planUsage, settingsDefaults, teamMembers } from '../data/workspaceData.js';

const tabs = ['General', 'Team & Roles', 'Notifications', 'Data & Analytics', 'AI Defaults', 'Security', 'Billing / Plan'];

function Settings() {
  const [activeTab, setActiveTab] = useState('General');
  const [settings, setSettings] = useState(settingsDefaults);
  const [members, setMembers] = useState(teamMembers);
  const [demoKeys, setDemoKeys] = useState(['wtg_demo_••••_9K2A']);
  const [feedback, setFeedback] = useState('');
  const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));

  return (
    <div className="overview-page settings-page">
      <section className="overview-hero"><div className="hero-copy"><span className="product-kicker">WTG Intelligence</span><h1>Settings</h1><p>Manage demo workspace preferences, team roles, notifications, AI defaults, security, and plan usage.</p></div><div className="hero-controls"><button className="button button--primary" type="button" onClick={() => setFeedback('Settings saved locally.')}>Save Changes</button></div></section>
      <div className="inline-status" aria-live="polite">{feedback || 'Demo-only settings. No external services are changed.'}</div>
      <div className="settings-tabs" role="tablist" aria-label="Settings sections">{tabs.map((tab) => <button role="tab" aria-selected={activeTab === tab} className={activeTab === tab ? 'is-selected' : ''} type="button" key={tab} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div>
      {activeTab === 'General' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Workspace</span><h2>General</h2></div></div><div className="assumption-grid">{[['Workspace Name','workspaceName'],['Workspace ID','workspaceId'],['Time Zone','timeZone'],['Currency','currency'],['Fiscal Year Start','fiscalStart'],['Default Start Page','startPage'],['Appearance','appearance']].map(([label,key]) => <label key={key}><span>{label}</span><input value={settings[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div></section>}
      {activeTab === 'Team & Roles' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Access</span><h2>Team &amp; Roles</h2></div><button className="button button--secondary" type="button" onClick={() => { setMembers((current) => [...current, { name: 'Demo Invitee', role: 'Viewer', status: 'Invited' }]); setFeedback('Team member invited locally.'); }}>Invite</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{members.map((member, index) => <tr key={`${member.name}-${index}`}><th scope="row">{member.name}</th><td><select value={member.role} onChange={(event) => setMembers((current) => current.map((item, i) => i === index ? { ...item, role: event.target.value } : item))}>{['Owner','Admin','Analyst','Executive Viewer','Viewer'].map((role) => <option key={role}>{role}</option>)}</select></td><td>{member.status}</td><td><button className="link-button" type="button" onClick={() => setFeedback(`${member.name} remove action mocked.`)}>Remove</button></td></tr>)}</tbody></table></div></section>}
      {activeTab === 'Notifications' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Alerts</span><h2>Notifications</h2></div></div><div className="settings-grid">{notificationCategories.map((item) => <article className="settings-card" key={item}><h3>{item}</h3>{['In App','Email','Slack'].map((channel) => <label key={channel}><input type="checkbox" defaultChecked={channel !== 'Slack'} />{channel}</label>)}</article>)}</div><label className="ask-box"><span>Quiet Hours</span><input defaultValue="6:00 PM - 8:00 AM ET" /></label></section>}
      {activeTab === 'Data & Analytics' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Demo Analytics</span><h2>Data &amp; Analytics</h2></div></div><div className="assumption-grid">{[['Default Reporting Period','reportingPeriod'],['Default Currency','currency'],['Forecast Horizon','forecastHorizon'],['Data Refresh Frequency','refreshFrequency'],['Retention Window','retentionWindow'],['Benchmark Comparison','benchmarkComparison'],['Anomaly Sensitivity','anomalySensitivity']].map(([label,key]) => <label key={key}><span>{label}</span><input value={settings[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div></section>}
      {activeTab === 'AI Defaults' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Local AI Demo Defaults</span><h2>AI Defaults</h2></div></div><div className="assumption-grid">{[['Insight Sensitivity','insightSensitivity'],['Minimum Confidence','minimumConfidence'],['Default Brief Style','briefStyle'],['Recommendation Threshold','recommendationThreshold'],['Saved Prompt History','promptHistory'],['Auto-generate Daily Brief','dailyBrief']].map(([label,key]) => <label key={key}><span>{label}</span><input value={settings[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div></section>}
      {activeTab === 'Security' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Security</span><h2>Security</h2></div></div><div className="forecast-grid">{[['Two-Factor Authentication','Enabled'],['SSO','Enterprise'],['Session Timeout','8 hours'],['Audit Logging','Enabled'],['API Access','Enabled'],['Data Retention','90 days']].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="report-list">{demoKeys.map((key) => <article className="report-item" key={key}><span className="report-icon">KEY</span><div><h3>Demo API Key</h3><span>{key}</span></div><button type="button" onClick={() => { setDemoKeys((current) => current.filter((item) => item !== key)); setFeedback('Demo key revoked locally.'); }}>Revoke</button></article>)}</div><button className="button button--secondary" type="button" onClick={() => { setDemoKeys((current) => [...current, `wtg_demo_••••_${current.length + 2}QZ`]); setFeedback('Masked demo key created locally.'); }}>Create Demo Key</button></section>}
      {activeTab === 'Billing / Plan' && <section className="panel"><div className="panel__header"><div><span className="eyebrow">Plan</span><h2>Billing / Plan</h2></div><span className="status-pill">Intelligence Scale / $299 month</span></div><div className="health-list">{planUsage.map((item) => <div className="health-metric" key={item.label}><div><span>{item.label}</span><strong>{item.value}</strong></div><div className="progress-track"><span style={{ width: `${item.percent}%` }} /></div></div>)}</div><div className="saved-question-list">{['Starter','Growth','Scale','Enterprise'].map((plan) => <button type="button" key={plan} onClick={() => setFeedback(`${plan} plan action mocked.`)}>{plan}</button>)}</div><p>Retention: 90 days. Billing actions are demo-only.</p></section>}
    </div>
  );
}

export default Settings;
